In [ ]:
import numpy as np

In [ ]:
arr = [10, 20, 30, 40, 50]

print(arr)

[10, 20, 30, 40, 50]


In [ ]:
arr2 = [
    [1, 2, 3],
    [4, 5, 6]
]

print(arr2)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
arr3 = [
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]

print(arr3)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

1
(5,)
int64
5


In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
number = [1, 2, 3, 5]
result = []
for x in number:
    result.append(x * 2)
print(result)

[2, 4, 6, 10]


In [ ]:
numbers = np.array([1, 2, 3, 4, 5])

result = numbers * 2

print(result)

[ 2  4  6  8 10]


In [ ]:
brr = [33,66,22,14,11,19,11]
print(np.sqrt(brr))

[5.74456265 8.1240384  4.69041576 3.74165739 3.31662479 4.35889894
 3.31662479]


In [ ]:
brr = [33,66,22,14,11,19,11]
print(np.square(brr))

[1089 4356  484  196  121  361  121]


In [ ]:
brr = [33,66,22,14,11,19,11]
print(np.log(brr))

[3.49650756 4.18965474 3.09104245 2.63905733 2.39789527 2.94443898
 2.39789527]


In [ ]:
brr = [33,66,22,14,11,19,11]
print(np.exp(brr))

[2.14643580e+14 4.60718663e+28 3.58491285e+09 1.20260428e+06
 5.98741417e+04 1.78482301e+08 5.98741417e+04]


In [ ]:
brr = [33,66,22,14,11,19,11]
print(np.cbrt(brr))

[3.20753433 4.04124002 2.80203933 2.41014226 2.22398009 2.66840165
 2.22398009]


In [ ]:
brr = [33,66,22,14,11,19,11]
arr = [1,2,3,4,5,6,7]
print(np.add(brr,arr))

[34 68 25 18 16 25 18]


In [ ]:
brr = [33,66,22,14,11,19,11]
arr = [1,2,3,4,5,6,7]
print(np.subtract(brr,arr))

[32 64 19 10  6 13  4]


In [ ]:
brr = [33,66,22,14,11,19,11]
arr = [1,2,3,4,5,6,7]
print(np.multiply(brr,arr))

[ 33 132  66  56  55 114  77]


In [ ]:
brr = [33,66,22,14,11,19,11]
arr = [1,2,3,4,5,6,7]
print(np.divide(brr,arr))

[33.         33.          7.33333333  3.5         2.2         3.16666667
  1.57142857]


In [ ]:
brr = [33,66,22,14,11,19,11]
arr = [1,2,3,4,5,6,7]
print(np.maximum(brr,arr))

[33 66 22 14 11 19 11]


In [ ]:
brr = [33,66,22,14,11,19,11]
arr = [1,2,3,4,5,6,7]
print(np.minimum(brr,arr))

[1 2 3 4 5 6 7]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a-b)

[-3 -3 -3]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)

[ 4 10 18]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a%b)

[1 2 3]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a**b)

[  1  32 729]


In [ ]:
marks =np.array([45,70,85,30,90])
passed =marks[marks>=40]
print(passed)

[45 70 85 90]


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.min(arr))

10


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.max(arr))

50


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.mean(arr))

30.0


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.median(arr))

30.0


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.std(arr))

14.142135623730951


In [ ]:
arr =np.array([10,20,30,40,50])
print(np.var(arr))

200.0


In [ ]:
arr =np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))

[5 7 9]


In [ ]:
arr =np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=1))

[ 6 15]


In [ ]:
arr =np.array([[1,2,3],[4,5,6]])
print(np.min(arr,axis=0))

[1 2 3]


In [ ]:
arr =np.array([[1,2,3],[4,5,6]])
print(np.min(arr,axis=1))

[1 4]


In [ ]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr =np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [ ]:
arr =np.array([[1,2,5],[3,4,6]])
print(arr.T)

[[1 3]
 [2 4]
 [5 6]]


In [ ]:
import numpy as np

marks = np.array([65, 75, 80, 90, 55])

print("Average:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard Deviation:", np.std(marks))

new_marks = marks + 5
print("New Marks:", new_marks)

Average: 73.0
Maximum: 90
Minimum: 55
Standard Deviation: 12.083045973594572
New Marks: [70 80 85 95 60]
